#super user permissions
sudo: required
language: generic
services:
    - docker

before_install:
    # . is the current directory
    # -t tag
    - docker build -t fanmixco/complex-fibonacci-docker-edition-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true fanmixco/complex-fibonacci-docker-edition-test npm run test

after_success:
    - docker build -t fanmixco/complex-fibonacci-docker-edition-client ./client
    - docker build -t fanmixco/complex-fibonacci-docker-edition-nginx ./nginx
    - docker build -t fanmixco/complex-fibonacci-docker-edition-server ./server
    - docker build -t fanmixco/complex-fibonacci-docker-edition-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Move those images and push them to Docker Hub.
    - docker push fanmixco/complex-fibonacci-docker-edition-client
    - docker push fanmixco/complex-fibonacci-docker-edition-nginx
    - docker push fanmixco/complex-fibonacci-docker-edition-server
    - docker push fanmixco/complex-fibonacci-docker-edition-worker



#deploy:
#

#- is an array

deploy:
    #edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    #app name
    app: "multi-docker"
    env: "MultiDocker-env"
    #s3-storage
    bucket_name: "elasticbeanstalk-us-east-2-195243960488"
    bucket_path: "docker-multi-v2"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
    #http://dockerreact-env.eba-vk7k8ges.us-east-2.elasticbeanstalk.com/
    #DockerReactExample-env.eba-apdipmnv.us-east-2.elasticbeanstalk.com